# custom helmfile name, uses different values file (2 replicas)
environments:
  test:
---
repositories:
 - name: grafana
   url: https://grafana.github.io/helm-charts

releases:
- name: grafana
  namespace: grafana
  chart: grafana/grafana
  values:
    - ./env/{{ .Environment.Name }}.yml